In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
mpl.rcParams['axes.unicode_minus'] = False 
plt.rcParams["font.family"] = "Malgun Gothic"
import warnings
warnings.filterwarnings("ignore")
import openpyxl

In [2]:
df_tl=pd.read_csv("C:/tl/youtube_불용어_6.csv")
df_tl.head()

   NO.                작성자  작성시간                              댓글내용 15568
0    1           MAHAWIRA  1일 전  New update : the best Graphics .
1    2    Lujazska Gaming  1일 전      Always the best Nice video..   NaN
2    5    Adrizal Adrizal  1일 전                   Orang mana min?   NaN
3    6          Iconic x2  1일 전         the video is so laggy bro   NaN
4    7  Eni Sasmita lubis  1일 전                       next update   NaN

In [3]:
df_tl.isnull()

         NO.    작성자   작성시간   댓글내용  15568
0      False  False  False  False  False
1      False  False  False  False   True
2      False  False  False  False   True
3      False  False  False  False   True
4      False  False  False  False   True
...      ...    ...    ...    ...    ...
15563  False  False  False  False   True
15564  False  False  False  False   True
15565  False  False  False  False   True
15566  False  False  False  False   True
15567  False  False  False  False   True

[15568 rows x 5 columns]

In [4]:
df_tl.isnull().sum()

NO.          0
작성자          0
작성시간         0
댓글내용         0
15568    15567
dtype: int64

In [5]:
df_tl_po1 = df_tl[df_tl['댓글내용'].str.contains(' po? ', na=False)]  # df_tl[조건식]
df_tl_po1

,NO.,작성자,작성시간,댓글내용,15568
76,92,Gary H. Field,1년 전,@YIREON SHIN Luid po kayu! ^_^,NaN
244,298,Jassie dela Cruz,1년 전,Bongbong po tayo...wag dilawan,NaN
320,429,Jay Ryan Macion,2주 전,Tamsak done po at bagong kaibigan pasukli nama...,NaN
327,453,charietala,5개월 전,Yes ganun nmn po talga basta family saka same ...,NaN
416,574,Jhulz Limsa,1년 전,Saan po makukuha ung barcode?,NaN
...,...,...,...,...,...
15532,24833,Aneliza Mendoza,9개월 전,Anung vessel po sinakyan nyo and what origin?,NaN
15535,24840,Vinz Ladion,9개월 전,Origin po Riyadh via PAL,NaN
15562,24939,Roydex Channel,2년 전,thanks po MamJasmine :),NaN
15564,24944,Roydex Channel,2년 전,"oi, Ms Lorena Thanks po :D",NaN
15566,24956,Cian Oclarit,2년 전,welcome to Bohol Sir. Maraming Magandang Tana...,NaN

In [6]:
df_tl_po1.to_excel(excel_writer='C:/tl/youtube_불용어/df_tl_po1_6sheet.xlsx')

In [7]:
index1=df_tl[df_tl['댓글내용'].str.contains(' po? ', na=False)].index
print(index1)

Int64Index([   76,   244,   320,   327,   416,   484,   486,   535,   598,
              599,
            ...
            15500, 15509, 15513, 15517, 15527, 15532, 15535, 15562, 15564,
            15566],
           dtype='int64', length=428)

In [8]:
df_tl = df_tl.drop(index1)

#####################################################

In [9]:
index2=df_tl[df_tl['댓글내용'].str.contains(' po. ', na=False)].index
print(index2)

Int64Index([   65,   481,   819,   844,   845,   849,   854,   874,  1349,
             1410,  1547,  1604,  2737,  2772,  2799,  2804,  2826,  2838,
             2936,  3259,  3333,  3335,  3403,  5277,  5664,  5705,  6380,
             6577,  8036,  8068,  9064,  9237, 11130, 11212, 11778, 11965,
            12099, 12118, 12263, 12329, 12392, 12448, 13753, 13803, 14772,
            14827, 15536],
           dtype='int64')

In [10]:
df_tl_po2 = df_tl[df_tl['댓글내용'].str.contains(' po. ', na=False)]  # df_tl[조건식]
df_tl_po2

,NO.,작성자,작성시간,댓글내용,15568
65,74,just a random weeb,5개월 전,Well cities dont just pop up out of no where,NaN
481,684,The Backpacker PH,1년 전,"Hi po! Yes, magkahiwalay. The terminal fee is ...",NaN
819,1499,Dada Koo,2년 전,Hahahahaha! Tama po! :D,NaN
844,1555,Dada Koo,2년 전,Hi po! Maraming slamat po! God bless,NaN
845,1556,Dada Koo,2년 전,Always welcome po! Thanks,NaN
849,1566,Dada Koo,2년 전,Alwats welcome po! Thank you much! God bless..,NaN
854,1571,Dada Koo,2년 전,Hi po! Thank you much! God bless,NaN
874,1660,Dada Koo,2년 전,Welcome po! :D,NaN
1349,2595,Franny Becker,1년 전,Bom dia!..\nHello Saudações 🇧🇷 estou muito fe...,NaN
1410,2683,Smende TV,4개월 전,In my book PRRD is the true Pilipino... Mabuha...,NaN
1547,3010,Me&Fam Moments,2개월 전,True po. Thank you ❤️,NaN
1604,3107,Edd 360,1개월 전,"Hello po, The hotel was in Angeles City Pampan...",NaN
2737,4683,arjie tv channel,1년 전,Wooow nice place poh god bless,NaN
2772,4754,Roydex Channel,10개월 전,"We'll do po, tnx din :)",NaN
2799,4821,Hachi,1년 전,Hello po! I will travel solo to Japan this Dec...,NaN
2804,4858,Rysha Garcia,1년 전,@Kenken De Leon Sir thank you somuch po. 😊,NaN
2826,4961,A M,1년 전,"@Kenken De Leon okay po, thank you.",NaN
2838,5018,Kenken De Leon,1년 전,@Sumesh Sudhamani i think so po. But try to ...,NaN
2936,5263,bidatoons channel 2016,4개월 전,ganda po! proud of this as kapampangan.thank y...,NaN
3259,6130,Tweety Jacky88,4개월 전,I love the OFW LOUNGE 😍😍😍.. Thank you poh tata...,NaN
3333,6308,Melody Summer,4개월 전,Nakakaproud po! 💕,NaN
3335,6312,John Samson,4개월 전,My President Rodrigo Roa Duterte god bless po. 👊👍,NaN
3403,6457,Lerma Jacinto,4개월 전,"With all due respect po, Sec. Vince Dizon, you...",NaN
5277,8943,Felloz Gaming Studio,8개월 전,Hello te hehehe. Safe trip po. Rest and relax ...,NaN
5664,9697,Nati x Donna,5개월 전,@tattle monkey Thanks po1 🥰,NaN
5705,9745,music 2020,2개월 전,"@Hochimin Rodriguez Hombre, me has tomado la...",NaN
6380,10420,Santina Maria,5개월 전,Oi Anderson bom dia!\n\nTambém gostei bastante...,NaN
6577,10617,Felipe Silva,1년 전,"Yeah, another guy witha huge salary eeching of...",NaN
8036,12084,Khaled E Ponera,2년 전,"Tunech Edward nipo poa ndugu, Magu anatupasua ...",NaN
8068,12116,Paulo Bertazzi,1년 전(수정됨),Dà gosto de ver a alegria e o orgulho que este...,NaN
9064,13112,Mago Aviador,2년 전,"Aproximação incrível!\nMuito lindo!\nParabéns,...",NaN
9237,13286,Antonio Monteiro da Silva Neto,2개월 전,Algum brasileiro por aqui?,NaN
11130,15184,Verónica B,2년 전,"Gracias Sam por este vídeo, es hermoso!!!",NaN
11212,15292,Casas abandonadas e variedades,1년 전,Boa noite esta história de vc me visitar ver m...,NaN
11778,16342,Emie Licudo 👉team chie-ka-dora,4개월 전,"Enjoy and keep safe po, support acezumi",NaN
11965,16784,Gelo Servito,2년 전,Mother X Daughter Collab tara poh samin,NaN
12099,17161,MaNang ROSE Vlog,1년 전,Tamsak poh team kakabsat,NaN
12118,17190,Airon Barbosa,1년 전,uma linda música amiga. Obrigado por compartil...,NaN
12263,17495,Jemmalyn Adriano,5개월 전,"very nice road trip po, i never seen the new c...",NaN
12329,17627,Ilocana Recipes,4개월 전,Drive safe po. God bless,NaN
12392,17789,Roydex Channel,2개월 전,Truth po! can't agree more :),NaN
12448,17937,Sander Phillips,4개월 전,@Jello Ace i’m not worried po. Mas dapat kan...,NaN
13753,20598,Mary Connie Suzon,2년 전,"good job, po! have a safe flight everyone",NaN
13803,20693,Roydex Channel,1개월 전,"yes po, if completed 19km of bike and pedestri...",NaN
14772,23175,Bernalyn Holto,2년 전,Enjoy poh thanks for sharing,NaN
14827,23315,Bea Bee,2년 전,sure po! godbless din :),NaN
15536,24844,Vinz Ladion,8개월 전,Stay safe po. Thanks,NaN

In [11]:
df_tl_po2.to_excel(excel_writer='C:/tl/youtube_불용어/df_tl_po2_6sheet.xlsx')

In [12]:
df_tl = df_tl.drop(index2)

#######################################################

In [13]:
index3=df_tl[df_tl['댓글내용'].str.contains(' po, ', na=False)].index
print(index3)

Int64Index([], dtype='int64')

In [14]:
df_tl_po3 = df_tl[df_tl['댓글내용'].str.contains(' po, ', na=False)]  # df_tl[조건식]
df_tl_po3

Empty DataFrame
Columns: [NO., 작성자, 작성시간, 댓글내용, 15568]
Index: []

In [72]:
df_tl_po3 = df_tl[df_tl['댓글내용'].str.contains(' po! ', na=False)]  # df_tl[조건식]
df_tl_po3

Empty DataFrame
Columns: [NO., 작성자, 작성시간, 댓글내용]
Index: []

In [15]:
df_tl.to_excel(excel_writer='C:/tl/시트별최종원본/df_tl_6sheet.xlsx')